from enum import IntEnum


class BillingStatus(IntEnum):
    DEFAULT = 0
    MESSAGE_OR_KEYBOARD_SENT_IN_A_SESSION_1 = 1
    MESSAGE_OR_KEYBOARD_SENT_IN_A_SESSION_2 = 2
    FREE_OUT_SESSION_MESSAGE_OR_KEYBOARD_3 = 3
    FREE_OUT_SESSION_MESSAGE_OR_KEYBOARD_4 = 4
    CHARGED_OUT_OF_SESSION = 5
